CREATE DATABASE IF NOT EXISTS HospitalVeterinari
CHARACTER SET utf8mb4
COLLATE utf8mb4_spanish_ci;

USE HospitalVeterinari;

CREATE TABLE IF NOT EXISTS Propietari (
IdPropietari 			INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
Nom				VARCHAR(15) NOT NULL,
Cognom			VARCHAR(30) NOT NULL DEFAULT '',
Telefon				CHAR(9) NOT NULL,
Direccion			VARCHAR(100)
)
ENGINE = INNODB;


CREATE TABLE IF NOT EXISTS Animal (
IdAnimal			INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
Nom				VARCHAR(15) NOT NULL,
Especie				VARCHAR(15) NOT NULL,
Raza 				VARCHAR(20) NOT NULL,
DataNaixement			DATE,
IdPropietari			INT UNSIGNED NOT NULL,
CONSTRAINT FOREIGN KEY (IdPropietari) REFERENCES Propietari(IdPropietari)
	ON DELETE CASCADE ON UPDATE CASCADE)
ENGINE = INNODB;


CREATE TABLE IF NOT EXISTS Veterinario (
IdVeterinario 			INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
Nom				VARCHAR(15) NOT NULL,
Especialidad			VARCHAR(20)NOT NULL,
DataInici			DATE,
IdSupervisor			INT UNSIGNED,
CONSTRAINT fk_veterinario_supervisor FOREIGN KEY (IdSupervisor) REFERENCES Veterinario(IdVeterinario)
ON DELETE SET NULL ON UPDATE CASCADE )
ENGINE = INNODB;


CREATE TABLE IF NOT EXISTS Medicament (
IdMedicament			INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NomComercial			VARCHAR(20) NOT NULL,
PrincipiActiu			VARCHAR(50) NOT NULL,
Fabricant			VARCHAR(15))
ENGINE = INNODB;


CREATE TABLE IF NOT EXISTS Tractament (
IdTractament			INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
CantidadMedicaments		INT UNSIGNED)
ENGINE = INNODB;


CREATE TABLE IF NOT EXISTS Medicament_Tractament (
IdTractament			INT UNSIGNED,
IdMedicament			INT UNSIGNED,
CONSTRAINT PK_Medicament_Tractament PRIMARY KEY (IdTractament, IdMedicament),
CONSTRAINT FOREIGN KEY (IdTractament) REFERENCES Tractament(IdTractament)
	ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FOREIGN KEY (IdMedicament) REFERENCES Medicament(IdMedicament)
	ON UPDATE CASCADE ON DELETE CASCADE)
ENGINE = INNODB;


CREATE TABLE IF NOT EXISTS Visita (
IdVisita				INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
Motivo				VARCHAR(100) NOT NULL,
DiagnosticInicial		VARCHAR(100),
IdTractament 			INT UNSIGNED,
CONSTRAINT fk_Visita_Tractament FOREIGN KEY (IdTractament) REFERENCES Tractament(IdTractament)
ON UPDATE CASCADE ON DELETE CASCADE)
ENGINE = INNODB;


CREATE TABLE IF NOT EXISTS Visita_Veterinario (
IdVisita				INT UNSIGNED NOT NULL,
IdVeterinario			INT UNSIGNED NOT NULL,
IdAnimal			INT UNSIGNED NOT NULL,
CONSTRAINT PRIMARY KEY (IdVisita, IdVeterinario),
CONSTRAINT fk_vv_visita FOREIGN KEY (IdVisita) REFERENCES Visita(IdVisita),
CONSTRAINT fk_vv_veterinari FOREIGN KEY (IdVeterinario) REFERENCES Veterinario(IdVeterinario),
CONSTRAINT fk_vv_animal FOREIGN KEY (IdAnimal) REFERENCES Animal(IdAnimal)) ENGINE = INNODB;
